# Generated by Django 3.0.1 on 2020-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=100)),
                ('customer_lastname', models.CharField(max_length=100)),
                ('customer_account_no', models.IntegerField(blank=True, null=True)),
                ('customer_contact_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
